#! /bin/sh

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

test_conv () {
    # FIXME: echo -n not portable
    echo -n "$1" > test.in
    if ./sexp-conv <test.in >test1.out ; then
	true
    else
	exit 1
    fi
    echo -n "$2" > test2.out

    if cmp test1.out test2.out ; then
	true
    else
	exit 1;
    fi
}

test_conv "3:foo" "foo" -a
test_conv "4:3des" '"3des"' -a
test_conv '"foo"' "foo" -a
test_conv '4:foo
' '"foo\n"'
test_conv '2:"\' '"\"\\"'
test_conv "()" "()"
test_conv '(foo bar baz)' '(foo bar
     baz)'
test_conv '; comment
()' "()"

test_conv "(foo[bar]foo)" "(foo [bar]foo)" -a

exit 0
